export const MAIN_ROUTE = "/"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const CART_ROUTE = "/cart"
export const SHOP_ROUTE = "/shop"
export const PRODUCT_ROUTE = "/product"
export const PROFILE_ROUTE = "/profile"
export const CATALOG_ROUTE = "/catalog"
export const SETTINGS_PAGE = "/settings"

export const REG_EX_PASSWORD = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/
export const ACCESS_TOKEN = "access_token"

export const LOGIN_API_URL = "login"
export const REGISTRATION_API_URL = "register"
export const GET_USER_DATA_API_URL = "get-user-data"
export const CATALOG_API_URL = "categories"

export const SET_CATALOG = "catalog/SET_CATALOG"
export const TOGGLE_CATALOG = "catalog/TOGGLE_CATALOG"
export const ADD_BREADCRUMBS_ITEM = "catalog/ADD_BREADCRUMBS_ITEM"
export const CLEAR_BREADCRUMBS = "catalog/CLEAR_BREADCRUMBS"
export const SET_USER = "profile/SET_USER"
export const SET_MESSAGE = "app/SET_MESSAGE"
export const SET_INITIALIZED = "app/SET_INITIALIZED"
export const SET_PRODUCTS = "product/SET_PRODUCTS"
export const SET_TOTAL_COUNT_PRODUCTS = "product/SET_TOTAL_COUNT_PRODUCTS"
export const SET_SELECTED_PRODUCT = "product/SET_SELECTED_PRODUCT"
export const SET_LAST_VIEWED_PRODUCTS = "product/SET_LAST_VIEWED_PRODUCTS"